<select id="profession" class="form-control" name="profession">
    <option value="">--Select Profession--</option>
    <option value="Accountant">Accountant</option>
    <option value="Actor">Actor</option>
    <option value="Actress">Actress</option>
    <option value="Atc">Air Traffic Controller</option>
    <option value="Architect">Architect</option>
    <option value="Artist">Artist</option>
    <option value="Attorney">Attorney</option>
    <option value="Banker">Banker</option>
    <option value="Bartender">Bartender</option>
    <option value="Barber">Barber</option>
    <option value="Bookkeeper">Bookkeeper</option>
    <option value="Builder">Builder</option>
    <option value="Businessman">Businessman</option>
    <option value="Businesswoman">Businesswoman</option>
    <option value="Businessperson">Businessperson</option>
    <option value="Butcher">Butcher</option>
    <option value="Carpenter">Carpenter</option>
    <option value="Cashier">Cashier</option>
    <option value="Chef">Chef</option>
    <option value="Dental Hygienist">Dental Hygienist</option>
    <option value="Dentist">Dentist</option>
    <option value="Designer">Designer</option>
    <option value="Developer">Developer</option>
    <option value="Dietician">Dietician</option>
    <option value="Eoctor">Doctor</option>
    <option value="Economist">Economist</option>
    <option value="Editor">Editor</option>
    <option value="Electrician">Electrician</option>
    <option value="Engineer">Engineer</option>
    <option value="Farmer">Farmer</option>
    <option value="Film Maker">Film Maker</option>
    <option value="Fisherman">Fisherman</option>
    <option value="Flight Attendant">Flight Attendant</option>
    <option value="Jeweler">Jeweler</option>
    <option value="Judge">Judge</option>
    <option value="Lawyer">Lawyer</option>
    <option value="Mechanic">Mechanic</option>
    <option value="Musician">Musician</option>
    <option value="Nutritionist">Nutritionist</option>
    <option value="Nurse">Nurse</option>
    <option value="Optician">Optician</option>
    <option value="Painter">Painter</option>
    <option value="Pharmacist">Pharmacist</option>
    <option value="Photographer">Photographer</option>
    <option value="Physician">Physician</option>
    <option value="Physician's Asistant">Physician's Asistant</option>
    <option value="Pilot">Pilot</option>
    <option value="Plumber">Plumber</option>
    <option value="Police Officer">Police Officer</option>
    <option value="Politician">Politician</option>
    <option value="Professor">Professor</option>
    <option value="Programmer">Programmer</option>
    <option value="Psychologist">Psychologist</option>
    <option value="Receptionist">Receptionist</option>
    <option value="Salesman">Salesman</option>
    <option value="Sales Person">Sales Person</option>
    <option value="Sales Woman">Sales Woman</option>
    <option value="Secretary">Secretary</option>
    <option value="Singer">Singer</option>
    <option value="Surgeon">Surgeon</option>
    <option value="Teacher">Teacher</option>
    <option value="Therapist">Therapist</option>
    <option value="Translator">Translator</option>
    <option value="Undertaker">Undertaker</option>
    <option value="Veterianrian">Veterianrian</option>
    <option value="Videographer">Videographer</option>
    <option value="Waiter">Waiter</option>
    <option value="Waitress">Waitress</option>
    <option value="Writer">Writer</option>
</select>